web:
  image: 864031815705.dkr.ecr.ap-northeast-1.amazonaws.com/docker-nginx-php/nginx
  ports:
    - 80:80
  links:
    - app:php

app:
  image: 864031815705.dkr.ecr.ap-northeast-1.amazonaws.com/docker-nginx-php/app
